name: Atualizacao_Quarta_Feira

on:
  schedule:
    # Roda às 08:00 AM (Horário de Brasília) toda quarta-feira
    - cron: '0 11 * * 3'
  workflow_dispatch: # Isso permite que você aperte um botão para rodar na hora que quiser

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copiar arquivos do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar bibliotecas necessárias
        run: |
          pip install pandas playwright
          playwright install chromium

      - name: Executar o Robô de Extração
        run: python coletor.py

      - name: Salvar dados atualizados no GitHub
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dados_epidemiologicos.csv
          git commit -m "Dados atualizados via Robo" || echo "Sem mudanças para salvar"
          git push
